//Localhost
//Landing
http://localhost:3000

//Contacts (all)
GET http://localhost:3000/contacts

//Contacts (single by ID) (John)
GET http://localhost:3000/contacts/6816b49cea9ea17f83b3b44e


### Get all contacts
GET http://localhost:3000/contacts
Content-Type: application/json

//onrender


### Get a single contact by ID (John)
GET http://localhost:3000/contacts/6816b49cea9ea17f83b3b44e
Content-Type: application/json

//Landing
https://personal-api-amx8.onrender.com

//Contacts (all)
https://personal-api-amx8.onrender.com/contacts

//Contacts (single by ID) (John)
https://personal-api-amx8.onrender.com/contacts/6816b49cea9ea17f83b3b44e